name: release-build

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    # TODO: Extract the project name from maven. 
    # Use mvn -q -Dexec.executable=echo -Dexec.args='${project.name}' --non-recursive exec:exec
    steps:
    - uses: actions/checkout@v2
    - name: Install graalvm
      uses: DeLaGuardo/setup-graalvm@3
      with:
        graalvm-version: '20.0.0.java11'
    - name: Install native-image
      run: gu install native-image
    - name: Set version
      run: ./mvnw versions:set -DnewVersion="${{ github.event.release.tag_name }}"
    - name: Build jvm jar
      run: ./mvnw package
    - name: Upload jvm
      id: upload-jar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./target/yq-${{ github.event.release.tag_name }}-runner.jar
        asset_name: yq-${{ github.event.release.tag_name }}.jar
        asset_content_type: application/octet-stream
    - name: Build native executable
      run: ./mvnw package -Dnative
    - name: Upload native executable
      id: upload-native-executable
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./target/yq-${{ github.event.release.tag_name }}-runner
        asset_name: yq-${{ github.event.release.tag_name }}-linux
        asset_content_type: application/octet-stream
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        commit-message: New version changes
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        title: Updates to release the new version.
        body: |
          Automatic version releasing.
        token: ${{ secrets.GITHUB_TOKEN }}
