name: release-build

on:
  workflow_dispatch
#  release:
#      types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    # TODO: Extract the project name from maven. 
    # Use mvn -q -Dexec.executable=echo -Dexec.args='${project.name}' --non-recursive exec:exec
    steps:
    - uses: actions/checkout@v2

    # Step that does that actual cache save and restore
    - uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Install graalvm
      uses: DeLaGuardo/setup-graalvm@5.0
      with:
        graalvm: '21.3.0'
        java: 'java17'

    - name: Install native-image
      run: gu install native-image

    - name: Build jvm jar
      run: ./mvnw package

    - name: Build native executable
      run: ./mvnw package -Dnative

    # Create a release
    - name: Run JReleaser
      uses: jreleaser/release-action@v2
      env:
        JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Persist logs
    - name: JReleaser release output
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: jreleaser-release
        path: |
          out/jreleaser/trace.log
          out/jreleaser/output.properties
